### ISSUE TITLE
Missing General Regulation

### ISSUE THREAD

**Issue by feliciofilipe** [cesium/seium.org#158]
We need a general regulation to make this button redirect to:

![image](https://user-images.githubusercontent.com/55213469/148380198-74adb115-7587-43fd-8017-0f4eb5bb1e77.png)

**Comment by mariajbp** [comment]
This will only be done in february/closer to the date, everything is uncertain right now 😭

**Comment by nelsonmestevao** [comment]
Closed by #82.
