### ISSUE TITLE
Navbar changes

### ISSUE THREAD

**Issue by mariajbp** [cesium/seium.org#190]
- [x] The font in the header is too big, should be smaller like in last year's website. These are prints from the same screen and everything is much larger.

![Captura de ecrã 2022-01-10, às 11 16 40](https://user-images.githubusercontent.com/32769382/148757537-5bd1d429-604a-4d82-b1a7-ba6eb67f8136.png)

![Captura de ecrã 2022-01-10, às 11 18 16](https://user-images.githubusercontent.com/32769382/148757753-6ee15aac-29d1-4b90-a770-e186d3b0d7bb.png)

- [x] Moonstone should be called login

- [x] Team page will not be available for now so it should temporarily be removed from the header

**Comment by feliciofilipe** [comment]
I fix this on #201, please review it
