### ISSUE TITLE
Login page fixes

### ISSUE THREAD

**Issue by mariajbp** [cesium/seium.org#192]
![Captura de ecrã 2022-01-10, às 11 24 51](https://user-images.githubusercontent.com/32769382/148758552-9b84b1ca-7047-4e61-b06b-02602a4ef2d3.png)

- [x] The link to go back to the website must have a left margin

- [x] The moonstone logo must be removed and everything centered*

*The reason for this is because the logo has poor quality and although it was in the original designs it should be removed.

**Comment by feliciofilipe** [comment]
With the logo looks better, also since I reckon we gonna replace the "Moonstone" entry from the navbar for a "Login" one, we are gonna eliminate all the references to the frontend original name "Moonstone" :(

Are you sure you do not prefer to replace by a high quality logo?

**Comment by nelsonmestevao** [comment]
> With the logo looks better, also since I reckon we gonna replace the "Moonstone" entry from the navbar for a "Login" one, we are gonna eliminate all the references to the frontend original name "Moonstone" :(
> 
> 
> 
> Are you sure you do not prefer to replace by a high quality logo? 

We could replace it with the SEI logo, it would make more sense. Moonstone is just our internal codename, what do you think? @feliciofilipe

**Comment by feliciofilipe** [comment]
Yeah sounds go @nelsonmestevao
