### ISSUE TITLE
Moonstone navigation bar fixes

### ISSUE THREAD

**Issue by mariajbp** [cesium/seium.org#193]
![Captura de ecrã 2022-01-10, às 11 29 28](https://user-images.githubusercontent.com/32769382/148759051-28176e70-04e9-49fc-96da-a7e875fb3dc3.png)

- [x] The **Back to SEI Website** link should have a right margin (matching the margin of the logout link)

- [x] Moonstone logo should be removed from the sidebar

**Comment by feliciofilipe** [comment]
Can we swap for the SEI Logo instead?

**Comment by nelsonmestevao** [comment]
>  Moonstone logo should be removed from the sidebar

Done in #281.
