### ISSUE TITLE
Remove underlined text

### ISSUE THREAD

**Issue by mariajbp** [cesium/seium.org#195]
Main page:
![Captura de ecrã 2022-01-10, às 11 35 08](https://user-images.githubusercontent.com/32769382/148759668-e1669dec-28c7-47db-86a2-2c4ee81fb179.png)

Hackathon page:
![Captura de ecrã 2022-01-10, às 11 35 37](https://user-images.githubusercontent.com/32769382/148759711-732619e6-ebfc-4d56-9c65-b773393ac8f4.png)

**Comment by feliciofilipe** [comment]
The design has the underline. Are you sure you want to remove them?

**Comment by mariajbp** [comment]
yes @feliciofilipe
