### ISSUE TITLE
Replace lorem ipsum on faqs page

### ISSUE THREAD

**Issue by feliciofilipe** [cesium/seium.org#209]
![image](https://user-images.githubusercontent.com/55213469/149504708-0ceb5175-4d6c-46c1-912d-ce55ddcd083b.png)

**Comment by nelsonmestevao** [comment]
@mariajbp @feliciofilipe 

What about?

> This list of frequently asked questions serves to complement the general rules that you can find here. Get in touch with the organizing team whenever a question arises and we will add answers to the most frequently asked questions here.

**Comment by mariajbp** [comment]
I added the suggested text, with a small change. In stead of _that you can find here_ I wrote _that you can find below_ since the general regulation is linked in the footer and it doesn't exist yet
