### ISSUE TITLE
Hero follow us not responding

### ISSUE THREAD

**Issue by nelsonmestevao** [cesium/seium.org#255]
At the moment, it is not possible to click in any of the following links: 

![image](https://user-images.githubusercontent.com/19409687/151718496-b7817282-1cce-48aa-a8ad-554721d3d0ad.png)

**Comment by nelsonmestevao** [comment]
It's fixed now :checkered_flag:

**Comment by nelsonmestevao** [comment]
It is not, sorry. It depends on the screen size.

**Comment by LAraujo7** [comment]
It's fixed 👌
