### ISSUE TITLE
Align "place" on awards listing

### ISSUE THREAD

**Issue by ruilopesm** [cesium/seium.org#511]
An example:
![image](https://github.com/cesium/seium.org/assets/76881129/7e31453b-df4f-4b17-afa8-70bfcdf8c50c)

**Comment by ShashwatPS** [comment]
Hey i would like to work on this issue, can  you assign it to me if possible ?

**Comment by ruilopesm** [comment]
@ShashwatPS Assigned ✅

**Comment by ShashwatPS** [comment]
Acutally i made a PR can you assign it to me again and review the PR ?
