### ISSUE TITLE
Fetch wheel tokens from env file 

### ISSUE THREAD

**Issue by MarioRodrigues10** [cesium/seium.org#562]
We are hardcoding the amount of tokens spent in lucky wheel.

![image](https://github.com/cesium/seium.org/assets/93675410/72518675-5a85-4fbd-8157-532fe2faca9c)

This could also be done by fetching the amount of tokens from the [backend](github.com/cesium/safira).

**Comment by Karan5807** [comment]
Can , I try to Solve this Issue
